name = "waku-with-cloudflare-sample"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-03"
compatibility_flags = [ "nodejs_als" ]

kv_namespaces = [
  { binding = "WAKU_SAMPLE", id = "YOUR_NAMESPACE_ID", preview_id = "YOUR_NAMESPACE_ID or YOUR_NAMESPACE_PREVIEW_ID" },
]
